CC=/usr/local/bin/g++
CC_FLAGS=
#INCLUDE_PATH=/usr/local/opt/openssl/include
#LIB_PATH=/usr/local/opt/openssl/lib

PROJECT_NAME=test_multithread2
SOURCE=$(PROJECT_NAME).cpp

#MYLIB_PATH=./mylib_C/
#MYLIB_NAME=mylib.c

ifeq ($(OS),Windows_NT)
	TARGET_FILE=$(PROJECT_NAME).exe
else
UNAME=${shell uname}
ifeq ($(UNAME),Darwin)
	TARGET_FILE=$(PROJECT_NAME)_for_mac
else
ifeq ($(UNAME),Linux)
	TARGET_FILE=$(PROJECT_NAME)_for_linux
else
	TARGET_FILE=$(PROJECT_NAME)
endif
endif
endif

all:	$(TARGET_FILE)

$(TARGET_FILE):	$(SOURCE) $(MYLIB_PATH)/$(MYLIB_NAME)
	$(CC) $(CC_FLAGS) -o$(TARGET_FILE) $(SOURCE) $(MYLIB_PATH)$(MYLIB_NAME)

clean:
	rm $(TARGET_FILE)	# Can not run on Windows

.PHONY:	all clean
